### ISSUE TITLE
Error reporter exception when tabs are present and a certain SyntaxHighlighter is used

### ISSUE THREAD

**Issue by skneko** [LanguageDev/Yoakke#49]
**Describe the bug**
When tabs are present at the beginning of a source code line, while using the custom `SyntaxHighlighter` available in `Yoakke.Reporting.Sample`, the error presenter finishes abruptly with an uncaught exception.

Example of exception:
```cs
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=System.Private.CoreLib
  StackTrace:
   at System.String.get_Chars(Int32 index)
   at Yoakke.Reporting.Present.TextDiagnosticsPresenter.WriteSourceLine(SourceLine line) in D:\dev\Yoakke\Sources\Core\Yoakke.Reporting\Present\TextDiagnosticsPresenter.cs:line 213
   at Yoakke.Reporting.Present.TextDiagnosticsPresenter.WriteSourceGroup(IEnumerable`1 infos) in D:\dev\Yoakke\Sources\Core\Yoakke.Reporting\Present\TextDiagnosticsPresenter.cs:line 157
   at Yoakke.Reporting.Present.TextDiagnosticsPresenter.Present(Diagnostics diagnostic) in D:\dev\Yoakke\Sources\Core\Yoakke.Reporting\Present\TextDiagnosticsPresenter.cs:line 84
   at Yoakke.Reporting.Sample.Program.Main(String[] args) in D:\dev\Yoakke\Sources\Examples\Yoakke.Reporting.Sample\Program.cs:line 58
```

**Which libraries does it affect?**
Namespace `Yoakke.Reporting.Present.TextDiagnosticsPresenter`, file `TextDiagnosticsPresenter.cs`.

Exceptions seem to arise in fragment `this.AdvanceCursor(ref lineCur, lineText[charIndex++])` at `TextDiagnosticsPresenter.cs`:213

**To Reproduce**
1. Go to file `Program.cs`, of project `Yoakke.Reporting.Sample`.
2. Change the value of the `src` variable to `new SourceFile("test.txt", "\nfunc foo() {\n\treturn 0;\n}\n")`. Notice this is the same program as before but there is not a tab in line 3 instead of spaces.
3. To discard an error related to the annotations having column indexes out of bounds, change the annotation "mistake made here" from (2,4) to (2,0) in line 56; `.WithSourceInfo(new Location(src, new Text.Range(new Position(2, 4), 6)), Severity.Error, "mistake made here");`

Full program (without comments):
```cs
using System;
using System.Collections.Generic;
using Yoakke.Reporting.Present;
using Yoakke.Text;

namespace Yoakke.Reporting.Sample
{
    internal class MyHighlighter : ISyntaxHighlighter
    {
        public SyntaxHighlightStyle Style { get; set; } = SyntaxHighlightStyle.Default;

        public IReadOnlyList<ColoredToken> GetHighlightingForLine(ISourceFile sourceFile, int line)
        {
            if (line == 1)
            {
                return new ColoredToken[]
                {
                new ColoredToken(0, 4, TokenKind.Keyword),
                new ColoredToken(5, 3, TokenKind.Name),
                };
            }
            else if (line == 2)
            {
                return new ColoredToken[]
                {
                new ColoredToken(4, 6, TokenKind.Keyword),
                new ColoredToken(11, 1, TokenKind.Literal),
                new ColoredToken(12, 1, TokenKind.Punctuation),
                };
            }
            return Array.Empty<ColoredToken>();
        }
    }

    internal class Program
    {
        private static void Main(string[] args)
        {
            var src = new SourceFile("test.txt", "\nfunc foo() {\n\treturn 0;\n}\n");

            var presenter = new TextDiagnosticsPresenter(Console.Error)
            {
                SyntaxHighlighter = new MyHighlighter(),
            };

            var diag = new Diagnostics()
                .WithCode("E001")
                .WithSeverity(Severity.Error)
                .WithMessage("you made a mistake")
                .WithSourceInfo(new Location(src, new Text.Range(new Position(2, 0), 6)), Severity.Error, "mistake made here");

            presenter.Present(diag);
        }
    }
}
```

**Expected behavior**
The program should not emit any unhandled exception and should terminate normally.

**Environment (please complete the following information):**
 - OS: Windows 10
 - .NET version: .NET 5

**Comment by LPeter1997** [comment]
I could reproduce the error, thank you for the detailed steps!

The problem is that `\t` counts as a single character, instead of applying some heuristic. This means, that when the syntax highlighter reports some error, we would expect the keyword return to start at column 1, and not 4. This is why we get an index out of bounds error here.

So fortunately this isn't strictly a logic error, but also signals that we are blindly using the data received from the user, which we definitely should not. My suggested solution would be to ignore everything that goes out of bounds.

**Comment by skneko** [comment]
Ah I didn't notice the syntax highlighter was using hardcoded position values, my mind was tunnel-focused on the positions of the annotations and discarded the highlighter...

After thinking it better, I feel like the exception may make sense, because if the host compiler generated a syntax highlighter with fixed positions that then those are not present/valid, that is weird and we lose guarantees that the colors are showing properly. We should, however, set the exception message to something more clear (or use a custom exception?) that explicitly says the positions inside the *syntax highlither* in particular are wrong, because all this time I've been confused thinking it was the positions of the diagnostics attached.

On the other hand, recovering from this error is so easy (not coloring the token or coloring it partially), and printing some colors is not something extremely important requiring strong guarantees, so... we could do without the exceptions. Maybe we can go crazy and have a toggleable strict mode for the presenter, so positions and other details are partially ignored in case of error (do-a-best-effort mode) OR exceptions are emitted as soon as something is off.

Thoughts? If we agree on a behavior I can try to tackle this with a PR.

**Comment by LPeter1997** [comment]
To be honest here, this is a case where I'd love to get an exception when debugging, and I'd definitely not want to crash my compiler in production for just missing colors. So your suggestion of a "strict" mode might not be that "crazy" after all.

So I'd either just ignore this error, or introduce an explicit option that would throw about this, an `ArgumentOutOfRangeException` with a custom message should be fine for this.

What I also concluded is that my sample is stupid, it was probably a quick hack to not have to write a lexer. No wonder about the confusion, who would expect hardcoded positions there? I'll write a small lexer when I get the time.

Feel free to either just ignore the error or do the strict-mode option, if you want to do a PR.
